const { transformAsync } = require('@babel/core');

/**
 * Turns the JSX generated by MDX to JS.
 *
 * @param {string} docsJsx
 * @param {string} filename
 * @returns {Promise<string>}
 */
async function jsxToJs(docsJsx, filename) {
  const result = await transformAsync(docsJsx, {
    filename,
    sourceMaps: true,
    plugins: [require.resolve('@babel/plugin-transform-react-jsx')],
  });
  if (!result) {
    throw new Error(`Something went wrong when compiling ${filename}`);
  }
  return result.code;
}

module.exports = { jsxToJs };
